// <auto-generated />
using CarPooling.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CarPooling.Migrations
{
    [DbContext(typeof(CarPoolingContext))]
    [Migration("20260608014500_AddTripFareAmount")]
    partial class AddTripFareAmount
    {
    }
}